module: src.client.agents.LmdeployAgent
parameters:
  model_name: "qwen1.5-7b"
  model_url: "http://192.168.237.147:23333"
  # Qwen1.5-7B-Chat: 192.168.237.147
  # Qwen1.5-7B-Chat: 192.168.237.147
  max_new_tokens: 512
  top_p: 0.8
  top_k: 100
  temperature: 0
  repetition_penalty: 1.0
  stop_words: ["<|im_end|>"]
